<?php include('header.php') ?>




	<main id="page-content" class="l-main" itemprop="mainContentOfPage">
	<section  class="l-section wpb_row height_medium"><div class="l-section-h i-cf"><div class="g-cols vc_row type_default valign_top"><div class="vc_col-sm-12 wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="w-grid media_coverage_tittles type_grid layout_1002" id="us_grid_1"><style id="us_grid_1_css">#us_grid_1 .w-grid-item:not(:last-child){margin-bottom:1.5rem}#us_grid_1 .g-loadmore{margin-top:1.5rem}</style><style>.layout_1002 .w-grid-item-h{}.layout_1002 .usg_post_title_1{font-size:1.4rem!important;line-height:40px!important}.layout_1002 .usg_hwrapper_1{color:#21234c!important;font-size:14px!important;margin:5px!important}.layout_1002 .usg_post_taxonomy_1{font-weight:700!important;text-transform:uppercase!important;font-size:16px!important;letter-spacing:1px!important}.layout_1002 .usg_post_date_1{font-size:16px!important}.layout_1002 .usg_post_image_1{margin-top:0.6rem!important}.layout_1002 .usg_post_content_1{font-size:0.9rem!important;line-height:1.7!important;margin-top:0.8rem!important}@media (max-width:600px){.layout_1002 .usg_post_title_1{font-size:1.2rem!important}}</style><div class="w-grid-list"><article class="w-grid-item size_1x1 post-1200 post type-post status-publish format-standard hentry category-media-coverage" data-id="1200">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../the-political-implications-of-the-coronavirus-pandemic-in-the-middle-east-experts-weigh-in-2/index.html">The Political Implications of the Corona virus Pandemic in the Middle East: Experts Weigh in</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../the-political-implications-of-the-coronavirus-pandemic-in-the-middle-east-experts-weigh-in-2/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2020-05-20T16:11:02+00:00">20th May 2020</time></div>	</div>
</article>
<article class="w-grid-item size_1x1 post-1126 post type-post status-publish format-standard hentry category-media-coverage" data-id="1126">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../coronavirus-and-the-gulf-economies-2/index.html">Coronavirus and the Gulf Economies</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../coronavirus-and-the-gulf-economies-2/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2020-04-09T14:13:01+00:00">9th April 2020</time></div>	</div>
</article>
<article class="w-grid-item size_1x1 post-1180 post type-post status-publish format-standard hentry category-media-coverage" data-id="1180">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../intellectual-property-rights-for-kuwaiti-artists-2/index.html">Intellectual Property Rights for Kuwaiti Artists</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../intellectual-property-rights-for-kuwaiti-artists-2/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2020-02-17T15:52:46+00:00">17th February 2020</time></div><div class="w-post-elm post_content usg_post_content_1">Your browser does not support the video tag.</div>	</div>
</article>
<article class="w-grid-item size_1x1 post-1193 post type-post status-publish format-standard hentry category-media-coverage" data-id="1193">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../kuwait-2020-and-beyond-challenges-and-opportunities-2/index.html">Kuwait 2020 and Beyond: Challenges and Opportunities</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../kuwait-2020-and-beyond-challenges-and-opportunities-2/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2019-12-04T16:01:48+00:00">4th December 2019</time></div>	</div>
</article>
<article class="w-grid-item size_1x1 post-1185 post type-post status-publish format-standard hentry category-media-coverage" data-id="1185">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../china-and-the-gulf-the-u-s-view/index.html">China and the Gulf: The U.S. View</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../china-and-the-gulf-the-u-s-view/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2019-10-16T15:56:03+00:00">16th October 2019</time></div>	</div>
</article>
<article class="w-grid-item size_1x1 post-1122 post type-post status-publish format-standard hentry category-media-coverage" data-id="1122">
	<div class="w-grid-item-h">
				<div class="w-hwrapper usg_hwrapper_2 align_left valign_top wrap "><h1 class="w-post-elm post_title usg_post_title_1 align_left entry-title color_link_inherit"><a href="../the-american-role-in-kuwaiti-iraqi-relations-2/index.html">The American Role in Kuwaiti-Iraqi Relations</a></h1></div><div class="w-hwrapper usg_hwrapper_1 align_left valign_top wrap "><div class="w-post-elm post_taxonomy usg_post_taxonomy_1 style_simple"><i class="fas fa-angle-double-right"></i><a href="../the-american-role-in-kuwaiti-iraqi-relations-2/index.html">Media Coverage</a></div><time class="w-post-elm post_date usg_post_date_1 entry-date published" datetime="2019-09-18T14:03:40+00:00">18th September 2019</time></div><div class="w-post-elm post_content usg_post_content_1">Your browser does not support the video tag.</div>	</div>
</article>
</div>	<div class="w-grid-json hidden" onclick='return {&quot;ajax_url&quot;:&quot;https:\/\/reconnresearch.com\/wp-admin\/admin-ajax.php&quot;,&quot;permalink_url&quot;:&quot;https:\/\/reconnresearch.com\/the-american-role-in-kuwaiti-iraqi-relations-2\/&quot;,&quot;action&quot;:&quot;us_ajax_grid&quot;,&quot;max_num_pages&quot;:1,&quot;infinite_scroll&quot;:0,&quot;template_vars&quot;:{&quot;query_args&quot;:{&quot;post_type&quot;:[&quot;post&quot;],&quot;tax_query&quot;:[{&quot;taxonomy&quot;:&quot;category&quot;,&quot;field&quot;:&quot;slug&quot;,&quot;terms&quot;:[&quot;media-coverage&quot;]}],&quot;post_status&quot;:[&quot;publish&quot;],&quot;post__not_in&quot;:[1121],&quot;orderby&quot;:{&quot;date&quot;:&quot;DESC&quot;},&quot;posts_per_page&quot;:&quot;10&quot;},&quot;post_id&quot;:1121,&quot;us_grid_index&quot;:1,&quot;us_grid_ajax_index&quot;:1,&quot;exclude_items&quot;:&quot;none&quot;,&quot;items_offset&quot;:&quot;1&quot;,&quot;items_layout&quot;:&quot;1002&quot;,&quot;type&quot;:&quot;grid&quot;,&quot;columns&quot;:&quot;1&quot;,&quot;img_size&quot;:&quot;default&quot;,&quot;overriding_link&quot;:&quot;none&quot;}}'></div>
</div></div></div></div></div></div></section>
</main>



<?php include('footer.php') ?>
